#include <stdint.h>
#include <stdbool.h>
#include <ti/drivers/GPIO.h>
#include "MotorDriver_mspm0.h"
#include "Board.h" /* generated by SysConfig */

/* Use the Board.h macro for pin_0. If your Board.h uses a different macro name,
   change Board_PIN_0 below to that macro. */
#ifndef PIN_0
#define PIN_0 Board_PIN_0
#endif

static MotorDriver motorDriver;

/* SysTick handler forward */
void SysTick_Handler(void);

int main(void)
{
    GPIO_init();

    MotorDriver_Init(&motorDriver, PIN_0);

    /* Example: 60% duty forward */
    MotorDriver_SetPWMDutyCycle(&motorDriver, 60U);
    MotorDriver_SetDirection(&motorDriver, MOTOR_FORWARD);

    /* Configure SysTick for 1ms tick (CMSIS SystemCoreClock expected) */
    if (SysTick_Config(SystemCoreClock / 1000U)) {
        while (1);
    }

    while (1) {
        /* main loop: update duty/dir as needed */
    }
}

void SysTick_Handler(void)
{
    MotorDriver_GeneratePWMOutput(&motorDriver);
}
