/* main.c
 * MSPM0G3507 - Timer-triggered ADC -> DMA -> UART streaming
 */

#include <stdint.h>
#include <stdbool.h>
#include "ti_msp_dl_config.h"   /* generated by SysConfig: prototypes for SYSCFG_DL_init, constants */
#include "Microphone.h"

/* Choose buffer length (must be even) */
#define BUFFER_LENGTH  1024

/* Shared ADC buffer declared in Microphone.h (Microphone.c defines it) */
extern uint16_t gMicADCBuffer[BUFFER_LENGTH]; /* 12-bit in 16-bit containers */

/* Forward */
static void start_acquisition(void);

int main(void)
{
    /* Basic device / driverlib syscfg init */
    SYSCFG_DL_init();

    /* At this point the SysConfig code has enabled power and performed basic GPIO config
       and peripheral base initialization (see your generated ti_msp_dl_config.c). */

    /* Initialize Microphone driver (links the ADC instance) */
    Microphone_Init(&gMicrophone, ADC12_0_INST, UART_0_INST, DMA_CH0);

    /* Configure DMA and callbacks inside Microphone_Init or Microphone_Start as shown below */
    start_acquisition();

    /* Let interrupts + DMA handle streaming */
    while (1) {
        __WFI(); /* wait for interrupt - low power */
    }
    return 0;
}

static void start_acquisition(void)
{
    /* Start the timer (the SysConfig init may have left it stopped). This is the timer that generates the ADC trigger. */
    DL_TimerA_start(TIMER_0_INST);

    /* Start ADC conversions + DMA inside microphone driver */
    Microphone_Start(&gMicrophone, gMicADCBuffer, BUFFER_LENGTH);
}
